// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/jinzhu/gorm/dialects/postgres"
	"github.com/stripe/stripe-go"
)

type Postgresql interface {
	IsPostgresql()
}

type Invoice struct {
	ID          uuid.UUID      `json:"id" gorm:"type:uuid;primary_key;default:uuid_generate_v4()"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
	DeletedAt   *time.Time     `json:"deletedAt"`
	CardToken   *string        `json:"cardToken"`
	ChargeToken *string        `json:"chargeToken"`
	CardData    *stripe.Card   `json:"cardData"`
	ChargeData  *stripe.Charge `json:"chargeData"`
	Items       []InvoiceItem  `json:"items"`
}

func (Invoice) IsPostgresql() {}

type InvoiceItem struct {
	ID          uuid.UUID    `json:"id" gorm:"type:uuid;primary_key;default:uuid_generate_v4()"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
	DeletedAt   *time.Time   `json:"deletedAt"`
	Invoice     *Invoice     `json:"invoice"`
	InvoiceID   uuid.UUID    `json:"invoiceID" gorm:"type:uuid"`
	Item        *Item        `json:"item"`
	ItemID      uuid.UUID    `json:"itemID" gorm:"type:uuid"`
	ItemPrice   *ItemPrice   `json:"itemPrice"`
	ItemPriceID uuid.UUID    `json:"itemPriceID" gorm:"type:uuid"`
	Options     []ItemOption `json:"options"`
}

func (InvoiceItem) IsPostgresql() {}

type ItemOption struct {
	ID            uuid.UUID      `json:"id" gorm:"type:uuid;primary_key;default:uuid_generate_v4()"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
	DeletedAt     *time.Time     `json:"deletedAt"`
	InvoiceItem   *InvoiceItem   `json:"invoiceItem"`
	InvoiceItemID uuid.UUID      `json:"invoiceItemID" gorm:"type:uuid"`
	OptionType    ItemOptionType `json:"optionType"`
	Values        string         `json:"values"`
}

func (ItemOption) IsPostgresql() {}

type ItemOptionType struct {
	ID        uuid.UUID       `json:"id" gorm:"type:uuid;primary_key;default:uuid_generate_v4()"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
	DeletedAt *time.Time      `json:"deletedAt"`
	Item      *Item           `json:"item"`
	ItemID    uuid.UUID       `json:"itemID" gorm:"type:uuid"`
	Key       string          `json:"key"`
	ValueType string          `json:"valueType"`
	Values    *postgres.Jsonb `json:"values"`
}

func (ItemOptionType) IsPostgresql() {}

type ItemPrice struct {
	ID         uuid.UUID  `json:"id" gorm:"type:uuid;primary_key;default:uuid_generate_v4()"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
	DeletedAt  *time.Time `json:"deletedAt"`
	Item       *Item      `json:"item"`
	ItemID     uuid.UUID  `json:"itemID" gorm:"type:uuid"`
	Price      int        `json:"price"`
	BeforeDate time.Time  `json:"beforeDate"`
	AfterDate  time.Time  `json:"afterDate"`
	Taxable    *bool      `json:"taxable"`
}

func (ItemPrice) IsPostgresql() {}

type NewInvoice struct {
	ID     *uuid.UUID       `json:"id"`
	Submit *bool            `json:"submit"`
	Items  []NewInvoiceItem `json:"items"`
}

type NewInvoiceItem struct {
	ID          *uuid.UUID      `json:"id"`
	ItemID      uuid.UUID       `json:"itemID"`
	ItemPriceID uuid.UUID       `json:"itemPriceID"`
	Options     []NewItemOption `json:"options"`
}

type NewItem struct {
	ID          *uuid.UUID          `json:"id"`
	Name        string              `json:"name"`
	Description *string             `json:"description"`
	Prices      []NewItemPrice      `json:"prices"`
	Options     []NewItemOptionType `json:"options"`
}

type NewItemOption struct {
	ID           *uuid.UUID     `json:"id"`
	OptionTypeID uuid.UUID      `json:"optionTypeID"`
	Values       postgres.Jsonb `json:"values"`
}

type NewItemOptionType struct {
	ID        *uuid.UUID     `json:"id"`
	Key       *string        `json:"key"`
	ValueType *string        `json:"valueType"`
	Values    postgres.Jsonb `json:"values"`
}

type NewItemPrice struct {
	ID         *uuid.UUID `json:"id"`
	Price      int        `json:"price"`
	BeforeDate time.Time  `json:"beforeDate"`
	AfterDate  time.Time  `json:"afterDate"`
}

type Paging struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}
